/* Generated By:JavaCC: Do not edit this line. MorseParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MorseParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Wort = 53;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int P = 1;
  /** Lexical state. */
  int P1 = 2;
  /** Lexical state. */
  int P2 = 3;
  /** Lexical state. */
  int R1 = 4;
  /** Lexical state. */
  int U1 = 5;
  /** Lexical state. */
  int U2 = 6;
  /** Lexical state. */
  int U3 = 7;
  /** Lexical state. */
  int R2 = 8;
  /** Lexical state. */
  int P4 = 9;
  /** Lexical state. */
  int P5 = 10;
  /** Lexical state. */
  int P6 = 11;
  /** Lexical state. */
  int R3 = 12;
  /** Lexical state. */
  int R4 = 13;
  /** Lexical state. */
  int U = 14;
  /** Lexical state. */
  int R = 15;
  /** Lexical state. */
  int END = 16;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\".\"",
    "\"_\"",
    "\"#\"",
    "\".\"",
    "\"#\"",
    "\"_\"",
    "\".\"",
    "\"_\"",
    "\"#\"",
    "\".\"",
    "\"#\"",
    "\"_\"",
    "\"_\"",
    "\"#\"",
    "\".\"",
    "\"_\"",
    "\".\"",
    "\"#\"",
    "\"_\"",
    "\".\"",
    "\"#\"",
    "\"#\"",
    "\"_\"",
    "\".\"",
    "\".\"",
    "\"#\"",
    "\"_\"",
    "\".\"",
    "\"#\"",
    "\"_\"",
    "\".\"",
    "\"#\"",
    "\"_\"",
    "\"#\"",
    "\".\"",
    "\"_\"",
    "\"#\"",
    "\".\"",
    "\"_\"",
    "\"#\"",
    "\".\"",
    "\"_\"",
    "\"_\"",
    "\"#\"",
    "\".\"",
    "\"#\"",
    "\"_\"",
    "\".\"",
    "\";\"",
  };

}
